//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować niewłaściwe zachowanie i zostaną utracone
//     w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceDywany
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DywanyForAllView", Namespace = "http://schemas.datacontract.org/2004/07/WcfServiceDywany")]
    public partial class DywanyForAllView : object
    {
        public int? IdPolozenia { get; internal set; }
        public int? Indeks { get; internal set; }
        public string Nazwa { get; internal set; }
        public int? Ilosc { get; internal set; }
        public string Grupa { get; internal set; }
        public bool? CzyNaPromocji { get; internal set; }
        public string NazwaPromocji { get; internal set; }
        public string NazwaPolozenia { get; internal set; }
        public int? IdPromocji { get; internal set; }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MiejscaForAllView", Namespace = "http://schemas.datacontract.org/2004/07/WcfServiceDywany")]
    public partial class MiejscaForAllView : object
    {
        public int IdMiejsca { get; internal set; }
        public string NazwaMiejsca { get; internal set; }
        public string NazwaPolozenia { get; internal set; }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PlusyForAllView", Namespace = "http://schemas.datacontract.org/2004/07/WcfServiceDywany")]
    public partial class PlusyForAllView : object
    {
        public int IdPlusu { get; internal set; }
        public decimal? Cena { get; internal set; }
        public int? Indeks { get; internal set; }
        public decimal? Ilosc { get; internal set; }
        public string Nazwa { get; internal set; }
        public string NazwaPolozenia { get; internal set; }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PracownicyForAllView", Namespace = "http://schemas.datacontract.org/2004/07/WcfServiceDywany")]
    public partial class PracownicyForAllView : object
    {
        public int IdPracownika { get; internal set; }
        public string Imie { get; internal set; }
        public string Nazwisko { get; internal set; }
        public int NumerPracownika { get; internal set; }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PromocjaForAllView", Namespace = "http://schemas.datacontract.org/2004/07/WcfServiceDywany")]
    public partial class PromocjaForAllView : object
    {
        public int? Indeks { get; internal set; }
        public decimal? Ilosc { get; internal set; }
        public decimal? Cena { get; internal set; }
        public string Nazwa { get; internal set; }
        public int IdPromocji { get; internal set; }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZdjeciaForAllView", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceDywany")]
    public partial class ZdjeciaForAllView : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Miejsce", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceDywany.Model")]
    public partial class Miejsce : object
    {
        
        private System.Collections.Generic.List<ServiceReferenceDywany.Dywan> DywanField;
        
        private int IdMiejscaField;
        
        private string NazwaMiejscaField;
        
        private string NazwaPolozeniaField;
        
        private System.Collections.Generic.List<ServiceReferenceDywany.Plusy> PlusyField;
        
        private System.Collections.Generic.List<ServiceReferenceDywany.Promocja> PromocjaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceDywany.Dywan> Dywan
        {
            get
            {
                return this.DywanField;
            }
            set
            {
                this.DywanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMiejsca
        {
            get
            {
                return this.IdMiejscaField;
            }
            set
            {
                this.IdMiejscaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazwaMiejsca
        {
            get
            {
                return this.NazwaMiejscaField;
            }
            set
            {
                this.NazwaMiejscaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazwaPolozenia
        {
            get
            {
                return this.NazwaPolozeniaField;
            }
            set
            {
                this.NazwaPolozeniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceDywany.Plusy> Plusy
        {
            get
            {
                return this.PlusyField;
            }
            set
            {
                this.PlusyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceDywany.Promocja> Promocja
        {
            get
            {
                return this.PromocjaField;
            }
            set
            {
                this.PromocjaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dywan", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceDywany.Model")]
    public partial class Dywan : object
    {
        
        private System.Nullable<decimal> CenaField;
        
        private System.Nullable<bool> CzyNaPromocjiField;
        
        private string GrupaField;
        
        private int IdDywanuField;
        
        private System.Nullable<int> IdPolozeniaField;
        
        private System.Nullable<int> IdPromocjiField;
        
        private System.Nullable<int> IdZdjeciaField;
        
        private System.Nullable<decimal> IloscField;
        
        private System.Nullable<int> IndeksField;
        
        private ServiceReferenceDywany.Miejsce MiejsceField;
        
        private string NazwaField;
        
        private ServiceReferenceDywany.Promocja PromocjaField;
        
        private ServiceReferenceDywany.Zdjecie ZdjecieField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Cena
        {
            get
            {
                return this.CenaField;
            }
            set
            {
                this.CenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CzyNaPromocji
        {
            get
            {
                return this.CzyNaPromocjiField;
            }
            set
            {
                this.CzyNaPromocjiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grupa
        {
            get
            {
                return this.GrupaField;
            }
            set
            {
                this.GrupaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDywanu
        {
            get
            {
                return this.IdDywanuField;
            }
            set
            {
                this.IdDywanuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPolozenia
        {
            get
            {
                return this.IdPolozeniaField;
            }
            set
            {
                this.IdPolozeniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPromocji
        {
            get
            {
                return this.IdPromocjiField;
            }
            set
            {
                this.IdPromocjiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdZdjecia
        {
            get
            {
                return this.IdZdjeciaField;
            }
            set
            {
                this.IdZdjeciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Ilosc
        {
            get
            {
                return this.IloscField;
            }
            set
            {
                this.IloscField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Indeks
        {
            get
            {
                return this.IndeksField;
            }
            set
            {
                this.IndeksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceDywany.Miejsce Miejsce
        {
            get
            {
                return this.MiejsceField;
            }
            set
            {
                this.MiejsceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceDywany.Promocja Promocja
        {
            get
            {
                return this.PromocjaField;
            }
            set
            {
                this.PromocjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceDywany.Zdjecie Zdjecie
        {
            get
            {
                return this.ZdjecieField;
            }
            set
            {
                this.ZdjecieField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plusy", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceDywany.Model")]
    public partial class Plusy : object
    {
        
        private System.Nullable<decimal> CenaField;
        
        private System.Nullable<int> IdMiejscaField;
        
        private int IdPlusuField;
        
        private System.Nullable<decimal> IloscField;
        
        private System.Nullable<int> IndeksField;
        
        private ServiceReferenceDywany.Miejsce MiejsceField;
        
        private string NazwaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Cena
        {
            get
            {
                return this.CenaField;
            }
            set
            {
                this.CenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdMiejsca
        {
            get
            {
                return this.IdMiejscaField;
            }
            set
            {
                this.IdMiejscaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPlusu
        {
            get
            {
                return this.IdPlusuField;
            }
            set
            {
                this.IdPlusuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Ilosc
        {
            get
            {
                return this.IloscField;
            }
            set
            {
                this.IloscField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Indeks
        {
            get
            {
                return this.IndeksField;
            }
            set
            {
                this.IndeksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceDywany.Miejsce Miejsce
        {
            get
            {
                return this.MiejsceField;
            }
            set
            {
                this.MiejsceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Promocja", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceDywany.Model")]
    public partial class Promocja : object
    {
        
        private System.Nullable<decimal> CenaField;
        
        private System.Collections.Generic.List<ServiceReferenceDywany.Dywan> DywanField;
        
        private System.Nullable<int> IdMiejscaField;
        
        private int IdPromocjiField;
        
        private System.Nullable<decimal> IloscField;
        
        private System.Nullable<int> IndeksField;
        
        private ServiceReferenceDywany.Miejsce MiejsceField;
        
        private string NazwaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Cena
        {
            get
            {
                return this.CenaField;
            }
            set
            {
                this.CenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceDywany.Dywan> Dywan
        {
            get
            {
                return this.DywanField;
            }
            set
            {
                this.DywanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdMiejsca
        {
            get
            {
                return this.IdMiejscaField;
            }
            set
            {
                this.IdMiejscaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPromocji
        {
            get
            {
                return this.IdPromocjiField;
            }
            set
            {
                this.IdPromocjiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Ilosc
        {
            get
            {
                return this.IloscField;
            }
            set
            {
                this.IloscField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Indeks
        {
            get
            {
                return this.IndeksField;
            }
            set
            {
                this.IndeksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceDywany.Miejsce Miejsce
        {
            get
            {
                return this.MiejsceField;
            }
            set
            {
                this.MiejsceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zdjecie", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceDywany.Model")]
    public partial class Zdjecie : object
    {
        
        private System.Collections.Generic.List<ServiceReferenceDywany.Dywan> DywanField;
        
        private int IdZdjeciaField;
        
        private string MiniaturkaField;
        
        private string NazwaZdjeciaField;
        
        private string UrlZdjeciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceDywany.Dywan> Dywan
        {
            get
            {
                return this.DywanField;
            }
            set
            {
                this.DywanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdZdjecia
        {
            get
            {
                return this.IdZdjeciaField;
            }
            set
            {
                this.IdZdjeciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Miniaturka
        {
            get
            {
                return this.MiniaturkaField;
            }
            set
            {
                this.MiniaturkaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazwaZdjecia
        {
            get
            {
                return this.NazwaZdjeciaField;
            }
            set
            {
                this.NazwaZdjeciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlZdjecia
        {
            get
            {
                return this.UrlZdjeciaField;
            }
            set
            {
                this.UrlZdjeciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pracownik", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceDywany.Model")]
    public partial class Pracownik : object
    {
        
        private int IdPracownikaField;
        
        private string ImieField;
        
        private string NazwiskoField;
        
        private int NumerPracownikaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPracownika
        {
            get
            {
                return this.IdPracownikaField;
            }
            set
            {
                this.IdPracownikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imie
        {
            get
            {
                return this.ImieField;
            }
            set
            {
                this.ImieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwisko
        {
            get
            {
                return this.NazwiskoField;
            }
            set
            {
                this.NazwiskoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumerPracownika
        {
            get
            {
                return this.NumerPracownikaField;
            }
            set
            {
                this.NumerPracownikaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDywany.IServiceDywany")]
    public interface IServiceDywany
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/GetDywany", ReplyAction="http://tempuri.org/IServiceDywany/GetDywanyResponse")]
        ServiceReferenceDywany.GetDywanyResponse GetDywany(ServiceReferenceDywany.GetDywanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/GetDywany", ReplyAction="http://tempuri.org/IServiceDywany/GetDywanyResponse")]
        System.Threading.Tasks.Task<ServiceReferenceDywany.GetDywanyResponse> GetDywanyAsync(ServiceReferenceDywany.GetDywanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/GetMiejsca", ReplyAction="http://tempuri.org/IServiceDywany/GetMiejscaResponse")]
        ServiceReferenceDywany.GetMiejscaResponse GetMiejsca(ServiceReferenceDywany.GetMiejscaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/GetMiejsca", ReplyAction="http://tempuri.org/IServiceDywany/GetMiejscaResponse")]
        System.Threading.Tasks.Task<ServiceReferenceDywany.GetMiejscaResponse> GetMiejscaAsync(ServiceReferenceDywany.GetMiejscaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/GetPlusy", ReplyAction="http://tempuri.org/IServiceDywany/GetPlusyResponse")]
        ServiceReferenceDywany.GetPlusyResponse GetPlusy(ServiceReferenceDywany.GetPlusyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/GetPlusy", ReplyAction="http://tempuri.org/IServiceDywany/GetPlusyResponse")]
        System.Threading.Tasks.Task<ServiceReferenceDywany.GetPlusyResponse> GetPlusyAsync(ServiceReferenceDywany.GetPlusyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/GetPracownicy", ReplyAction="http://tempuri.org/IServiceDywany/GetPracownicyResponse")]
        ServiceReferenceDywany.GetPracownicyResponse GetPracownicy(ServiceReferenceDywany.GetPracownicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/GetPracownicy", ReplyAction="http://tempuri.org/IServiceDywany/GetPracownicyResponse")]
        System.Threading.Tasks.Task<ServiceReferenceDywany.GetPracownicyResponse> GetPracownicyAsync(ServiceReferenceDywany.GetPracownicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/GetPromocja", ReplyAction="http://tempuri.org/IServiceDywany/GetPromocjaResponse")]
        ServiceReferenceDywany.GetPromocjaResponse GetPromocja(ServiceReferenceDywany.GetPromocjaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/GetPromocja", ReplyAction="http://tempuri.org/IServiceDywany/GetPromocjaResponse")]
        System.Threading.Tasks.Task<ServiceReferenceDywany.GetPromocjaResponse> GetPromocjaAsync(ServiceReferenceDywany.GetPromocjaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/GetZdjecia", ReplyAction="http://tempuri.org/IServiceDywany/GetZdjeciaResponse")]
        ServiceReferenceDywany.GetZdjeciaResponse GetZdjecia(ServiceReferenceDywany.GetZdjeciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/GetZdjecia", ReplyAction="http://tempuri.org/IServiceDywany/GetZdjeciaResponse")]
        System.Threading.Tasks.Task<ServiceReferenceDywany.GetZdjeciaResponse> GetZdjeciaAsync(ServiceReferenceDywany.GetZdjeciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/AddMiejsce", ReplyAction="http://tempuri.org/IServiceDywany/AddMiejsceResponse")]
        ServiceReferenceDywany.AddMiejsceResponse AddMiejsce(ServiceReferenceDywany.AddMiejsceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/AddMiejsce", ReplyAction="http://tempuri.org/IServiceDywany/AddMiejsceResponse")]
        System.Threading.Tasks.Task<ServiceReferenceDywany.AddMiejsceResponse> AddMiejsceAsync(ServiceReferenceDywany.AddMiejsceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/AddDywan", ReplyAction="http://tempuri.org/IServiceDywany/AddDywanResponse")]
        ServiceReferenceDywany.AddDywanResponse AddDywan(ServiceReferenceDywany.AddDywanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/AddDywan", ReplyAction="http://tempuri.org/IServiceDywany/AddDywanResponse")]
        System.Threading.Tasks.Task<ServiceReferenceDywany.AddDywanResponse> AddDywanAsync(ServiceReferenceDywany.AddDywanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/AddPracownik", ReplyAction="http://tempuri.org/IServiceDywany/AddPracownikResponse")]
        ServiceReferenceDywany.AddPracownikResponse AddPracownik(ServiceReferenceDywany.AddPracownikRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/AddPracownik", ReplyAction="http://tempuri.org/IServiceDywany/AddPracownikResponse")]
        System.Threading.Tasks.Task<ServiceReferenceDywany.AddPracownikResponse> AddPracownikAsync(ServiceReferenceDywany.AddPracownikRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/AddPlusy", ReplyAction="http://tempuri.org/IServiceDywany/AddPlusyResponse")]
        ServiceReferenceDywany.AddPlusyResponse AddPlusy(ServiceReferenceDywany.AddPlusyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/AddPlusy", ReplyAction="http://tempuri.org/IServiceDywany/AddPlusyResponse")]
        System.Threading.Tasks.Task<ServiceReferenceDywany.AddPlusyResponse> AddPlusyAsync(ServiceReferenceDywany.AddPlusyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/AddZdjecie", ReplyAction="http://tempuri.org/IServiceDywany/AddZdjecieResponse")]
        ServiceReferenceDywany.AddZdjecieResponse AddZdjecie(ServiceReferenceDywany.AddZdjecieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/AddZdjecie", ReplyAction="http://tempuri.org/IServiceDywany/AddZdjecieResponse")]
        System.Threading.Tasks.Task<ServiceReferenceDywany.AddZdjecieResponse> AddZdjecieAsync(ServiceReferenceDywany.AddZdjecieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/AddPromocja", ReplyAction="http://tempuri.org/IServiceDywany/AddPromocjaResponse")]
        ServiceReferenceDywany.AddPromocjaResponse AddPromocja(ServiceReferenceDywany.AddPromocjaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDywany/AddPromocja", ReplyAction="http://tempuri.org/IServiceDywany/AddPromocjaResponse")]
        System.Threading.Tasks.Task<ServiceReferenceDywany.AddPromocjaResponse> AddPromocjaAsync(ServiceReferenceDywany.AddPromocjaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDywany", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDywanyRequest
    {
        
        public GetDywanyRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDywanyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDywanyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceDywany.DywanyForAllView> GetDywanyResult;
        
        public GetDywanyResponse()
        {
        }
        
        public GetDywanyResponse(System.Collections.Generic.List<ServiceReferenceDywany.DywanyForAllView> GetDywanyResult)
        {
            this.GetDywanyResult = GetDywanyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMiejsca", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMiejscaRequest
    {
        
        public GetMiejscaRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMiejscaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMiejscaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceDywany.MiejscaForAllView> GetMiejscaResult;
        
        public GetMiejscaResponse()
        {
        }
        
        public GetMiejscaResponse(System.Collections.Generic.List<ServiceReferenceDywany.MiejscaForAllView> GetMiejscaResult)
        {
            this.GetMiejscaResult = GetMiejscaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPlusy", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPlusyRequest
    {
        
        public GetPlusyRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPlusyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPlusyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceDywany.PlusyForAllView> GetPlusyResult;
        
        public GetPlusyResponse()
        {
        }
        
        public GetPlusyResponse(System.Collections.Generic.List<ServiceReferenceDywany.PlusyForAllView> GetPlusyResult)
        {
            this.GetPlusyResult = GetPlusyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPracownicy", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPracownicyRequest
    {
        
        public GetPracownicyRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPracownicyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPracownicyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceDywany.PracownicyForAllView> GetPracownicyResult;
        
        public GetPracownicyResponse()
        {
        }
        
        public GetPracownicyResponse(System.Collections.Generic.List<ServiceReferenceDywany.PracownicyForAllView> GetPracownicyResult)
        {
            this.GetPracownicyResult = GetPracownicyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPromocja", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPromocjaRequest
    {
        
        public GetPromocjaRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPromocjaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPromocjaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceDywany.PromocjaForAllView> GetPromocjaResult;
        
        public GetPromocjaResponse()
        {
        }
        
        public GetPromocjaResponse(System.Collections.Generic.List<ServiceReferenceDywany.PromocjaForAllView> GetPromocjaResult)
        {
            this.GetPromocjaResult = GetPromocjaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetZdjecia", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetZdjeciaRequest
    {
        
        public GetZdjeciaRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetZdjeciaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetZdjeciaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceDywany.ZdjeciaForAllView> GetZdjeciaResult;
        
        public GetZdjeciaResponse()
        {
        }
        
        public GetZdjeciaResponse(System.Collections.Generic.List<ServiceReferenceDywany.ZdjeciaForAllView> GetZdjeciaResult)
        {
            this.GetZdjeciaResult = GetZdjeciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddMiejsce", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddMiejsceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceDywany.Miejsce miejsce;
        
        public AddMiejsceRequest()
        {
        }
        
        public AddMiejsceRequest(ServiceReferenceDywany.Miejsce miejsce)
        {
            this.miejsce = miejsce;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddMiejsceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddMiejsceResponse
    {
        
        public AddMiejsceResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDywan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddDywanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceDywany.Dywan dywan;
        
        public AddDywanRequest()
        {
        }
        
        public AddDywanRequest(ServiceReferenceDywany.Dywan dywan)
        {
            this.dywan = dywan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDywanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddDywanResponse
    {
        
        public AddDywanResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPracownik", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddPracownikRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceDywany.Pracownik pracownik;
        
        public AddPracownikRequest()
        {
        }
        
        public AddPracownikRequest(ServiceReferenceDywany.Pracownik pracownik)
        {
            this.pracownik = pracownik;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPracownikResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddPracownikResponse
    {
        
        public AddPracownikResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPlusy", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddPlusyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceDywany.Plusy plusy;
        
        public AddPlusyRequest()
        {
        }
        
        public AddPlusyRequest(ServiceReferenceDywany.Plusy plusy)
        {
            this.plusy = plusy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPlusyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddPlusyResponse
    {
        
        public AddPlusyResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddZdjecie", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddZdjecieRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceDywany.Zdjecie zdjecie;
        
        public AddZdjecieRequest()
        {
        }
        
        public AddZdjecieRequest(ServiceReferenceDywany.Zdjecie zdjecie)
        {
            this.zdjecie = zdjecie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddZdjecieResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddZdjecieResponse
    {
        
        public AddZdjecieResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPromocja", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddPromocjaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceDywany.Promocja promocja;
        
        public AddPromocjaRequest()
        {
        }
        
        public AddPromocjaRequest(ServiceReferenceDywany.Promocja promocja)
        {
            this.promocja = promocja;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPromocjaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddPromocjaResponse
    {
        
        public AddPromocjaResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceDywanyChannel : ServiceReferenceDywany.IServiceDywany, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceDywanyClient : System.ServiceModel.ClientBase<ServiceReferenceDywany.IServiceDywany>, ServiceReferenceDywany.IServiceDywany
    {
        
        /// <summary>
        /// Wdróż tę metodę częściową, aby skonfigurować punkt końcowy usługi.
        /// </summary>
        /// <param name="serviceEndpoint">Punkt końcowy do skonfigurowania</param>
        /// <param name="clientCredentials">Poświadczenia klienta</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceDywanyClient() : 
                base(ServiceDywanyClient.GetDefaultBinding(), ServiceDywanyClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceDywany.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceDywanyClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceDywanyClient.GetBindingForEndpoint(endpointConfiguration), ServiceDywanyClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceDywanyClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceDywanyClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceDywanyClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceDywanyClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceDywanyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReferenceDywany.GetDywanyResponse GetDywany(ServiceReferenceDywany.GetDywanyRequest request)
        {
            return base.Channel.GetDywany(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceDywany.GetDywanyResponse> GetDywanyAsync(ServiceReferenceDywany.GetDywanyRequest request)
        {
            return base.Channel.GetDywanyAsync(request);
        }
        
        public ServiceReferenceDywany.GetMiejscaResponse GetMiejsca(ServiceReferenceDywany.GetMiejscaRequest request)
        {
            return base.Channel.GetMiejsca(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceDywany.GetMiejscaResponse> GetMiejscaAsync(ServiceReferenceDywany.GetMiejscaRequest request)
        {
            return base.Channel.GetMiejscaAsync(request);
        }
        
        public ServiceReferenceDywany.GetPlusyResponse GetPlusy(ServiceReferenceDywany.GetPlusyRequest request)
        {
            return base.Channel.GetPlusy(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceDywany.GetPlusyResponse> GetPlusyAsync(ServiceReferenceDywany.GetPlusyRequest request)
        {
            return base.Channel.GetPlusyAsync(request);
        }
        
        public ServiceReferenceDywany.GetPracownicyResponse GetPracownicy(ServiceReferenceDywany.GetPracownicyRequest request)
        {
            return base.Channel.GetPracownicy(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceDywany.GetPracownicyResponse> GetPracownicyAsync(ServiceReferenceDywany.GetPracownicyRequest request)
        {
            return base.Channel.GetPracownicyAsync(request);
        }
        
        public ServiceReferenceDywany.GetPromocjaResponse GetPromocja(ServiceReferenceDywany.GetPromocjaRequest request)
        {
            return base.Channel.GetPromocja(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceDywany.GetPromocjaResponse> GetPromocjaAsync(ServiceReferenceDywany.GetPromocjaRequest request)
        {
            return base.Channel.GetPromocjaAsync(request);
        }
        
        public ServiceReferenceDywany.GetZdjeciaResponse GetZdjecia(ServiceReferenceDywany.GetZdjeciaRequest request)
        {
            return base.Channel.GetZdjecia(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceDywany.GetZdjeciaResponse> GetZdjeciaAsync(ServiceReferenceDywany.GetZdjeciaRequest request)
        {
            return base.Channel.GetZdjeciaAsync(request);
        }
        
        public ServiceReferenceDywany.AddMiejsceResponse AddMiejsce(ServiceReferenceDywany.AddMiejsceRequest request)
        {
            return base.Channel.AddMiejsce(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceDywany.AddMiejsceResponse> AddMiejsceAsync(ServiceReferenceDywany.AddMiejsceRequest request)
        {
            return base.Channel.AddMiejsceAsync(request);
        }
        
        public ServiceReferenceDywany.AddDywanResponse AddDywan(ServiceReferenceDywany.AddDywanRequest request)
        {
            return base.Channel.AddDywan(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceDywany.AddDywanResponse> AddDywanAsync(ServiceReferenceDywany.AddDywanRequest request)
        {
            return base.Channel.AddDywanAsync(request);
        }
        
        public ServiceReferenceDywany.AddPracownikResponse AddPracownik(ServiceReferenceDywany.AddPracownikRequest request)
        {
            return base.Channel.AddPracownik(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceDywany.AddPracownikResponse> AddPracownikAsync(ServiceReferenceDywany.AddPracownikRequest request)
        {
            return base.Channel.AddPracownikAsync(request);
        }
        
        public ServiceReferenceDywany.AddPlusyResponse AddPlusy(ServiceReferenceDywany.AddPlusyRequest request)
        {
            return base.Channel.AddPlusy(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceDywany.AddPlusyResponse> AddPlusyAsync(ServiceReferenceDywany.AddPlusyRequest request)
        {
            return base.Channel.AddPlusyAsync(request);
        }
        
        public ServiceReferenceDywany.AddZdjecieResponse AddZdjecie(ServiceReferenceDywany.AddZdjecieRequest request)
        {
            return base.Channel.AddZdjecie(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceDywany.AddZdjecieResponse> AddZdjecieAsync(ServiceReferenceDywany.AddZdjecieRequest request)
        {
            return base.Channel.AddZdjecieAsync(request);
        }
        
        public ServiceReferenceDywany.AddPromocjaResponse AddPromocja(ServiceReferenceDywany.AddPromocjaRequest request)
        {
            return base.Channel.AddPromocja(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceDywany.AddPromocjaResponse> AddPromocjaAsync(ServiceReferenceDywany.AddPromocjaRequest request)
        {
            return base.Channel.AddPromocjaAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceDywany))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceDywany))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.103:59121/ServiceDywany.svc");
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceDywanyClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceDywany);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceDywanyClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceDywany);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceDywany,
        }
    }
}
