//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceDywany.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promocja()
        {
            this.Dywan = new HashSet<Dywan>();
        }
    
        public int IdPromocji { get; set; }
        public Nullable<int> Indeks { get; set; }
        public Nullable<int> IdMiejsca { get; set; }
        public string Nazwa { get; set; }
        public Nullable<decimal> Ilosc { get; set; }
        public Nullable<decimal> Cena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dywan> Dywan { get; set; }
        public virtual Miejsce Miejsce { get; set; }
    }
}
