//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceDywany.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zdjecie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zdjecie()
        {
            this.Dywan = new HashSet<Dywan>();
        }
    
        public int IdZdjecia { get; set; }
        public string NazwaZdjecia { get; set; }
        public string UrlZdjecia { get; set; }
        public string Miniaturka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dywan> Dywan { get; set; }
    }
}
